// src/frameworks/vue/template/src/components/SiteNavigation.vue
<template>
  <header>
    <router-link
      v-for="(navItem, idx) in navigation"
      :key="idx"
      :to="navItem.to"
    >
      {{ navItem.text }}
    </router-link>
  </header>
</template>

<script>
export default {
  name: 'SiteNavigation',
  props: {
    navigation: Object,
  },
};
</script>

<style lang="scss">
  header {
    display: flex;
    justify-content: flex-end;
    margin-bottom: 2rem;
    padding: 1rem;
    border-bottom: 1px solid;
  }
</style>

// src/frameworks/react/template/src/components/SiteNavigation.jsx
import React from 'react';
import {
  Link,
} from 'react-router-dom';

// If a component wanted to use custom styles instead of rely on page styles, import then here
// import 'SiteNavigation.scss';

export default ({ navigation }) => (
  <header>
    {navigation.map((navItem, idx) => (
      <Link
        key={idx}
        to={navItem.to}
      >{navItem.text}</Link>
    ))}
  </header>
);
