// src/frameworks/react/template/src/App.jsx
import { Provider } from 'react-redux';
import {
  BrowserRouter as Router,
  Route,
  Switch,
} from 'react-router-dom';

// Import Redux store if required
import store from './store';

// Import layout components
import SiteNavigation from './components/SiteNavigation.jsx';

// Import pages
import Home from './pages/Home.jsx';
import NotFound from './pages/NotFound.jsx';

// Import assets
import logo from './assets/img/fpo-test.png';

export default () => {
  const pageHeader = 'Fusion Alliance Starter Kit';
  const navLinks = [
    {
      to: '/',
      text: 'Home',
    },
    {
      to: '/oops',
      text: '404 Page',
    },
  ];

  return (
    <div className="App">
      <Provider store={store}>
        <Router>
          <SiteNavigation navigation={navLinks} />
            <img alt="React logo" src={logo} />
          <Switch>
            <Route exact path="/">
              <Home />
            </Route>
            <Route path="*">
              <NotFound />
            </Route>
          </Switch>
        </Router>
      </Provider>
    </div>
  );
};

// src/frameworks/vue/template/src/App.vue
<template>
  <div id="app">
    <site-navigation :navigation="navLinks" />
    <img alt="Vue logo" src="./assets/img/fpo-test.png">
    <router-view />
  </div>
</template>

<script>

export default {
  name: 'App',
  data() {
    return {
      pageHeader: 'Fusion Alliance Starter Kit',
      navLinks: [
        {
          to: '/',
          text: 'Home',
        },
      ],
    };
  },
  mounted() {

  },
  methods: {
    log(str) {
      console.log(str);
    },
  },
};
</script>

<style lang="scss">
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
}
</style>
